paths:
  /api/vault/create/{userId}/{email}:
    post:
      summary: Initialize a user
      tags:
        - User
      parameters:
        - name: userId
          in: path
          required: true
          example: 550e8400-e29b-41d4-a716-446655440000
          schema:
            type: string
        - name: email
          in: path
          required: true
          example: dunsin@gmail.com
          schema:
            type: string
      responses:
        '201':
          description: User initialized successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: 09796deb-8ad1-4167-9ae5-0602ddfb2925
                      email:
                        type: string
                        example: dunsin2@gmail.com
                      upstreamUserId:
                        type: string
                        example: 550e8400-e29b-41d4-a716-446655440002
                      fireblocksVaultId:
                        type: string
                        example: '7'
                      createdAt:
                        type: string
                        format: date-time
                        example: 2025-09-22T09:41:42.412Z
        '400':
          description: Invalid request payload or parameters
        '401':
          description: Unauthorized — invalid transaction PIN
        '500':
          description: Internal server error

  /api/asset/activate-base-assets/{userId}:
    post:
      summary: Activate base assets for a vault
      tags:
        - Assets
      parameters:
        - name: userId
          in: path
          required: true
          example: 550e8400-e29b-41d4-a716-446655440000
          schema:
            type: string
      responses:
        '200':
          description: Base assets activated successfully
          # content:
          #   application/json:
          #     schema:
          #       type: object
          #       properties:
          #         status:
          #           type: string
          #           example: success
          #         data:
          #           type: array
          #           items:
          #             type: object
          #             properties:
          #               name:
          #                 type: string
          #                 example: Bitcoin Test
          #               symbol:
          #                 type: string
          #                 example: BTC_TEST
          #               address:
          #                 type: string
          #                 example: tb1qpw0nmwculpgudd863cp8shqq3vzpk7czyddsa0
          #               walletId:
          #                 type: string
          #                 example: 9ee5040f-391a-4a0f-9415-9a5d23e736cf
        '400':
          description: Invalid request
        '500':
          description: Internal server error

  # /api/asset/activate-asset/{assetId}:
  #   post:
  #     summary: Activate a specific asset
  #     tags:
  #       - Assets
  #     parameters:
  #       - name: assetId
  #         in: path
  #         required: true
  #         schema:
  #           type: string
  #     responses:
  #       '200':
  #         description: Asset activated successfully
  #       '400':
  #         description: Invalid asset ID
  #       '500':
  #         description: Internal server error

  /api/asset/get-assets/{userId}:
    get:
      summary: Get all asset addresses of a user
      tags:
        - Assets
      parameters:
        - name: userId
          in: path
          required: true
          example: 550e8400-e29b-41d4-a716-446655440000
          schema:
            type: string
      responses:
        '200':
          description: List of assets
        '404':
          description: User not found
        '500':
          description: Internal server error

  # /api/asset/get-asset/{userId}/{assetId}:
  #   get:
  #     summary: Get a specific asset for a user
  #     tags:
  #       - Assets
  #     parameters:
  #       - name: userId
  #         in: path
  #         required: true
  #         schema:
  #           type: string
  #       - name: assetId
  #         in: path
  #         required: true
  #         schema:
  #           type: string
  #     responses:
  #       '200':
  #         description: Asset details
  #       '404':
  #         description: Asset or user not found
  #       '500':
  #         description: Internal server error

  /api/asset/addresses/{userId}:
    get:
      summary: Get all asset addresses for a user
      tags:
        - Addresses
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of addresses
        '404':
          description: User not found
        '500':
          description: Internal server error

  # /api/asset/address/{userId}/{assetId}:
  #   get:
  #     summary: Get the address for a specific asset
  #     tags:
  #       - Addresses
  #     parameters:
  #       - name: userId
  #         in: path
  #         required: true
  #         schema:
  #           type: string
  #       - name: assetId
  #         in: path
  #         required: true
  #         schema:
  #           type: string
  #     responses:
  #       '200':
  #         description: Asset address
  #       '404':
  #         description: Address not found
  #       '500':
  #         description: Internal server error

  /api/asset/balances/{userId}:
    get:
      summary: Get balances of all assets for a user
      tags:
        - Balances
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of balances
        '404':
          description: User not found
        '500':
          description: Internal server error

  # /api/asset/balance/{userId}/{assetId}:
  #   get:
  #     summary: Get the balance of a specific asset
  #     tags:
  #       - Balances
  #     parameters:
  #       - name: userId
  #         in: path
  #         required: true
  #         example: 550e8400-e29b-41d4-a716-446655440000
  #         schema:
  #           type: string
  #       - name: assetId
  #         in: path
  #         required: true
  #         schema:
  #           type: string
  #     responses:
  #       '200':
  #         description: Asset balance
  #       '404':
  #         description: Balance not found
  #       '500':
  #         description: Internal server error
