paths:
  /api/vault/create/{userId}/{email}:
    post:
      summary: Initialize a User
      tags:
        - User
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: email
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: user initialized successfully
        '400':
          description: Invalid request payload or parameters
        '401':
          description: Unauthorized — invalid transaction PIN
        '500':
          description: Internal server error
